---
title: "HW10"
author: "Christian Sallinger"
date: "8 6 2021"
output: pdf_document
---

## 1. Exponential family

Show that the one-parameter exponential family has a monotone likelihood ratio in a sufficent statistic $T(\textbf{X})$ if the natural parameter $w(\theta)$ is a non-decreasing function in $\theta$.

\textbf{Solution:}

## 2. Confidence interval 1

In the June 1986 issue of Consumer Reports, some data on the calorie content of beef hot dogs is given. Here are the numbers of calories in 20 different hot dog brands:

$$
186, 181, 176 149,184,190,158,139,175,148,152,111,141,153,190,157,131,149,135,132.
$$

Assume that the numbers are from a normal distribution with mean $\mu$ and variance $\sigma^2$, both unknown. Use \texttt{R} to obtain a $90 \%$ confidence interval for the mean number of calories $\mu$.

\textbf{Solution:}

## 3. Confidence interval 2

Suppose $X_1,\dots, X_n$ are i.i.d. with pdf

$$
f(x\mid \lambda, \eta)
=
\begin{cases}
\lambda e^{-\lambda(x-\eta)}, & x > \eta \\
0, & \text{otherwise}
\end{cases}
$$

where $\lambda$ and $\eta$ are positive parameters with $\eta$ known but $\lambda$ unknown. Find the MLE of $\lambda$ and construct a $(1-\alpha)100\%$ confidence interval for $\lambda$ when $n$ is assumed to be large.

\textbf{Solution:}

## 4. confidence interval 3

Use \texttt{R} to generate a random sample $X_1,\dots, X_n$ from $Pois(1)$ distribution (for $n = 30$ and $n = 100$). Compute the $90\%$ confidence interval for $\lambda$, check if it contains the true value of $\lambda = 1$, and repeat this $10000$ times. What is the fraction of simulations for which the confidence interval covers $\lambda$?

\textbf{Solution:}

## 5. Boxplots and quantiles

Two novel randomized algorithms (A and B) are to be compared regarding their runtimes. Both algorithms were executed $n$ times. The runtimes (in seconds) are stored in the file $\texttt{algorithms.Rdata}$

(a) Set the working directory and load the data using $\texttt{load}()$. Create a boxplot to compare the running times. Color the boxes and add proper notations (axes notations, title, etc.). More info via $\texttt{?boxplot}$

(b) Comment on the following statements / questions only using the graphic.

\quad \quad  (a) The first quartile of the times in A was about?

\quad \quad (b) The interquartile range of the times in B is about trice the interquartile range     of A.

\quad \quad  (c) Is $n = 100$?
 
\quad \quad (d) More than half of the running times in B were faster than $3/4$ of the running    times in A.

\quad \quad (e) At least $50\%$ in A were faster than the $25\%$ slowest in B.

\quad \quad (f) at least $60\%$ in A were faster than the $25\%$ slowest in B.

(c) Regarding the runtimes

$$
23.7, 13.7, 7.6, 9.0, 44.3, 3.5, 2.2, 34.2
$$

which are a subset of B, find all empirical (a) medians, (b) first quartiles and (c) $2/3$-quantiles (not using $\mathrm{R}$).

\textbf{Solution:}