---
title: "HW6"
author: "Sallinger Christian"
date: "4 5 2021"
output: pdf_document
---


## 1. Method of moment estimator

Let $X_1, \dots, X_n$ be a random sample from a population with pdf

$$
f(x)
=
\begin{cases}
\frac{\theta x^{\theta -1}}{3^\theta}, & 0 < x <3 \\
0, & \text{otherwise}
\end{cases}
$$

where $\theta \in \mathbb{R}^+$ is an unkown parameter.

\noindent
(a) Show that the method of moments estimator for $\theta$ is $T_n = \frac{\bar{X}}{3-\bar{X}}$.

\noindent
(b) Find the limiting distribution of $\frac{T_n-\theta}{1/\sqrt{n}}$ as $n \to \infty$.

\textbf{Solution:}


## 2. Box of candles

There are blue and red candles in a box. Probability that a randomly chosen candle is blue is $\frac{1}{1+2a}$, for $a > 0$. Based on a sample of sample size $n$, find the maximum likelihood estimator (MLE) $\hat{a}$ of the parameter $a$.

\textbf{Solution:}

## 3. Point estimator statistics: Comparison

Let $X_1, \dots, X_n$ be i.i.d. uniform $(0,\theta)$, with unknown parameter $\theta >0$.

\noindent
(a) Show that the method of moments estimator of $\theta$ is $2\bar{X}$ and the MLE of $\theta$ is $X_{(n)} = \max_{1\leq i\leq n}X_i$.

\noindent
(b) Compare the mean-square errors of the two estimators. Which of the estimator should be preferred if any? Explain your reasoning.

\textbf{Solution:}

## 4. Unbiased estimators

Let $\hat{a}$ and $\hat{b}$ be unbiased estimators of unknown parameters $a$ and $b$ respectively.

\noindent
(a) Check if $\alpha \hat{a}+\beta\hat{b}$ is an unbiased estimator of the parameter $\alpha a + \beta b$, where $\alpha, \beta \in \mathbb{R}$.

\noindent
(b) Is $\hat{a}^2$ an unbiased estimator of $a^2$?

\noindent
(c) Based on the following measurements of a side of a square (in millimeters)

$$
15, 17,16, 16, 17, 14
$$

find and unbiased estimator of the area.

\textbf{Solution:}

## 5.Rayleigh distribution

Let $X_1,\dots,X_n$ be a random sample with Rayleigh distribution

$$
f(x\mid \theta)
=
\begin{cases}
\frac{x}{\theta^2}e^{-\frac{x^2}{2\theta^2}}, & x\geq 0 \\
0, & x<0
\end{cases}
$$

where $\theta >0$ is unknown.

\noindent
(a) Find the method of moments estimator of $\theta$.

\noindent
(b) Find the MLE of $\theta$ and its asymptotic variance.

\textit{Hint:} Show that the first two moments are $\mathbb{E}X = \theta\sqrt{\frac{\pi}{2}}$ and $\mathbb{E}X^2 = 2\theta^2$.

\textbf{Solution:}